name: Set-up LDC to target Linux AArch64
description: Adds a working aarch64-linux-gnu target to LDC.

runs:
  using: composite
  steps:
    - name: Install GCC
      shell: bash
      run: sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        mkdir -p $HOME/.ldc/
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
        cat << EOF | tee $HOME/.ldc/ldc2.conf
        "aarch64-.*-linux-gnu":
        {
            switches = [
                "-defaultlib=phobos2-ldc,druntime-ldc",
                "-gcc=aarch64-linux-gnu-gcc",
            ];
            post-switches = [
                "-I$HOME/ldc2-$LDC_VERSION-linux-aarch64/import",
            ];
            lib-dirs = [
                "$HOME/ldc2-$LDC_VERSION-linux-aarch64/lib",
            ];
        };
        EOF
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
        curl -LO https://github.com/ldc-developers/ldc/releases/download/v$LDC_VERSION/ldc2-$LDC_VERSION-linux-aarch64.tar.xz
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
        tar -xf ./ldc2-$LDC_VERSION-linux-aarch64.tar.xz -C $HOME
