name: GTK builds

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - triple: 'x86_64-linux-gnu'
            target: 'linux'

          - triple: 'aarch64-linux-gnu'
            target: 'linux'

        # Doesn't work, gtk_d doesn't support those platforms.
        # - triple: 'x86_64-windows-msvc'
        #   target: 'windows'

        # - triple: 'x86_64-apple-darwin'
        #   target: 'macos'

        # - triple: 'arm64-apple-macos'
        #   target: 'macos'

    name: Build GTK for ${{ matrix.triple }}

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update APT repos
        run: sudo apt-get update

      - name: Set-up D compiler
        uses: ./.github/actions/setup-d-compiler
        with:
          target-triple: ${{ matrix.triple }}

      - name: Write version file
        uses: ./.github/actions/write-version-file

      - name: Build
        run: dub build -b release-debug --compiler=ldc2 --arch ${{ matrix.triple }} :gtk-frontend

      - name: Move files around for artifcation
        uses: ./.github/actions/rename-files
        with:
          build-tag: gtk-${{ matrix.triple }}

      - uses: actions/upload-artifact@v4
        with:
          name: sideloader-gtk-${{ matrix.triple }}
          path: |
            ${{github.workspace}}/bin/*
